apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: taler-exchange
  name: taler-exchange
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: taler-exchange
  template:
    metadata:
      labels:
        app: taler-exchange
    spec:
      containers:
        - image: docker.io/yonggan/taler-exchange
          name: taler-exchange
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: "/etc/taler/taler.conf"
              name: taler-conf
              readOnly: true
            - mountPath: "/etc/taler/secrets/exchange-db.secret.conf"
              name: db-conf
              readOnly: true
      volumes:
        - name: taler-conf
          secret:
            secretName: taler 

        - name: db-conf
          secret:
            secretName: db-conf
